// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/streamforge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is the input record. Phases 1-2 carry it as JSON on Kafka for
// debuggability; this message becomes the wire format in Phase 3 alongside the
// gRPC services below.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	EventTime     int64                  `protobuf:"varint,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	IngestTime    int64                  `protobuf:"varint,6,opt,name=ingest_time,json=ingestTime,proto3" json:"ingest_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_streamforge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Event) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Event) GetIngestTime() int64 {
	if x != nil {
		return x.IngestTime
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_streamforge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_streamforge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type Assignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ready           bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`                                                   // false until the cluster has first formed
	KafkaPartitions []int32                `protobuf:"varint,2,rep,packed,name=kafka_partitions,json=kafkaPartitions,proto3" json:"kafka_partitions,omitempty"` // Kafka partitions THIS worker consumes
	KeyBuckets      []int32                `protobuf:"varint,3,rep,packed,name=key_buckets,json=keyBuckets,proto3" json:"key_buckets,omitempty"`                // hash buckets THIS worker owns
	NumBuckets      int32                  `protobuf:"varint,4,opt,name=num_buckets,json=numBuckets,proto3" json:"num_buckets,omitempty"`                       // total bucket space
	// bucket_owner_addr[b] = shuffle address of the worker owning bucket b.
	// The router uses this to decide local-vs-remote and to dial the owner.
	BucketOwnerAddr         []string `protobuf:"bytes,5,rep,name=bucket_owner_addr,json=bucketOwnerAddr,proto3" json:"bucket_owner_addr,omitempty"`
	LastCompletedCheckpoint int64    `protobuf:"varint,6,opt,name=last_completed_checkpoint,json=lastCompletedCheckpoint,proto3" json:"last_completed_checkpoint,omitempty"` // 0 until Phase 4
	// epoch increments on every membership change (join/death). A worker that
	// sees a higher epoch resets to the last checkpoint with the new assignment.
	Epoch         int64 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_streamforge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Assignment) GetKafkaPartitions() []int32 {
	if x != nil {
		return x.KafkaPartitions
	}
	return nil
}

func (x *Assignment) GetKeyBuckets() []int32 {
	if x != nil {
		return x.KeyBuckets
	}
	return nil
}

func (x *Assignment) GetNumBuckets() int32 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

func (x *Assignment) GetBucketOwnerAddr() []string {
	if x != nil {
		return x.BucketOwnerAddr
	}
	return nil
}

func (x *Assignment) GetLastCompletedCheckpoint() int64 {
	if x != nil {
		return x.LastCompletedCheckpoint
	}
	return 0
}

func (x *Assignment) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_streamforge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reassigned    bool                   `protobuf:"varint,1,opt,name=reassigned,proto3" json:"reassigned,omitempty"`
	Assignment    *Assignment            `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_streamforge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetReassigned() bool {
	if x != nil {
		return x.Reassigned
	}
	return false
}

func (x *HeartbeatResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

// CheckpointBarrier identifies one checkpoint round (the aligned barrier).
type CheckpointBarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  int64                  `protobuf:"varint,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointBarrier) Reset() {
	*x = CheckpointBarrier{}
	mi := &file_proto_streamforge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointBarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointBarrier) ProtoMessage() {}

func (x *CheckpointBarrier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointBarrier.ProtoReflect.Descriptor instead.
func (*CheckpointBarrier) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{6}
}

func (x *CheckpointBarrier) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

// CheckpointAck is a worker's response to CommitCheckpoint: its state snapshot
// plus the offsets that snapshot corresponds to, captured together at the same
// quiescent point so state and offsets advance as one unit.
type CheckpointAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CheckpointId     int64                  `protobuf:"varint,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	KafkaOffsets     map[int32]int64        `protobuf:"bytes,3,rep,name=kafka_offsets,json=kafkaOffsets,proto3" json:"kafka_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // partition -> next offset
	StateSnapshotUri string                 `protobuf:"bytes,4,opt,name=state_snapshot_uri,json=stateSnapshotUri,proto3" json:"state_snapshot_uri,omitempty"`
	StagedOutputs    []string               `protobuf:"bytes,5,rep,name=staged_outputs,json=stagedOutputs,proto3" json:"staged_outputs,omitempty"` // empty until Phase 6
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckpointAck) Reset() {
	*x = CheckpointAck{}
	mi := &file_proto_streamforge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointAck) ProtoMessage() {}

func (x *CheckpointAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointAck.ProtoReflect.Descriptor instead.
func (*CheckpointAck) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{7}
}

func (x *CheckpointAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CheckpointAck) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

func (x *CheckpointAck) GetKafkaOffsets() map[int32]int64 {
	if x != nil {
		return x.KafkaOffsets
	}
	return nil
}

func (x *CheckpointAck) GetStateSnapshotUri() string {
	if x != nil {
		return x.StateSnapshotUri
	}
	return ""
}

func (x *CheckpointAck) GetStagedOutputs() []string {
	if x != nil {
		return x.StagedOutputs
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_streamforge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{8}
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_proto_streamforge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssignmentRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// ShuffleRequest carries an event redirected to the worker that owns its key.
type ShuffleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleRequest) Reset() {
	*x = ShuffleRequest{}
	mi := &file_proto_streamforge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleRequest) ProtoMessage() {}

func (x *ShuffleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamforge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleRequest.ProtoReflect.Descriptor instead.
func (*ShuffleRequest) Descriptor() ([]byte, []int) {
	return file_proto_streamforge_proto_rawDescGZIP(), []int{10}
}

func (x *ShuffleRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_proto_streamforge_proto protoreflect.FileDescriptor

const file_proto_streamforge_proto_rawDesc = "" +
	"\n" +
	"\x17proto/streamforge.proto\x12\vstreamforge\"\xab\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"event_time\x18\x05 \x01(\x03R\teventTime\x12\x1f\n" +
	"\vingest_time\x18\x06 \x01(\x03R\n" +
	"ingestTime\"H\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"K\n" +
	"\x10RegisterResponse\x127\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x17.streamforge.AssignmentR\n" +
	"assignment\"\x8d\x02\n" +
	"\n" +
	"Assignment\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12)\n" +
	"\x10kafka_partitions\x18\x02 \x03(\x05R\x0fkafkaPartitions\x12\x1f\n" +
	"\vkey_buckets\x18\x03 \x03(\x05R\n" +
	"keyBuckets\x12\x1f\n" +
	"\vnum_buckets\x18\x04 \x01(\x05R\n" +
	"numBuckets\x12*\n" +
	"\x11bucket_owner_addr\x18\x05 \x03(\tR\x0fbucketOwnerAddr\x12:\n" +
	"\x19last_completed_checkpoint\x18\x06 \x01(\x03R\x17lastCompletedCheckpoint\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x03R\x05epoch\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"l\n" +
	"\x11HeartbeatResponse\x12\x1e\n" +
	"\n" +
	"reassigned\x18\x01 \x01(\bR\n" +
	"reassigned\x127\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x17.streamforge.AssignmentR\n" +
	"assignment\"8\n" +
	"\x11CheckpointBarrier\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\x03R\fcheckpointId\"\xba\x02\n" +
	"\rCheckpointAck\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\x03R\fcheckpointId\x12Q\n" +
	"\rkafka_offsets\x18\x03 \x03(\v2,.streamforge.CheckpointAck.KafkaOffsetsEntryR\fkafkaOffsets\x12,\n" +
	"\x12state_snapshot_uri\x18\x04 \x01(\tR\x10stateSnapshotUri\x12%\n" +
	"\x0estaged_outputs\x18\x05 \x03(\tR\rstagedOutputs\x1a?\n" +
	"\x11KafkaOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"3\n" +
	"\x14GetAssignmentRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\":\n" +
	"\x0eShuffleRequest\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.streamforge.EventR\x05event2\xef\x01\n" +
	"\vCoordinator\x12G\n" +
	"\bRegister\x12\x1c.streamforge.RegisterRequest\x1a\x1d.streamforge.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.streamforge.HeartbeatRequest\x1a\x1e.streamforge.HeartbeatResponse\x12K\n" +
	"\rGetAssignment\x12!.streamforge.GetAssignmentRequest\x1a\x17.streamforge.Assignment2\xdd\x01\n" +
	"\x06Worker\x12G\n" +
	"\x11PrepareCheckpoint\x12\x1e.streamforge.CheckpointBarrier\x1a\x12.streamforge.Empty\x12N\n" +
	"\x10CommitCheckpoint\x12\x1e.streamforge.CheckpointBarrier\x1a\x1a.streamforge.CheckpointAck\x12:\n" +
	"\aShuffle\x12\x1b.streamforge.ShuffleRequest\x1a\x12.streamforge.EmptyB5Z3github.com/Mxs8513/StreamForge/internal/proto;protob\x06proto3"

var (
	file_proto_streamforge_proto_rawDescOnce sync.Once
	file_proto_streamforge_proto_rawDescData []byte
)

func file_proto_streamforge_proto_rawDescGZIP() []byte {
	file_proto_streamforge_proto_rawDescOnce.Do(func() {
		file_proto_streamforge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streamforge_proto_rawDesc), len(file_proto_streamforge_proto_rawDesc)))
	})
	return file_proto_streamforge_proto_rawDescData
}

var file_proto_streamforge_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_streamforge_proto_goTypes = []any{
	(*Event)(nil),                // 0: streamforge.Event
	(*RegisterRequest)(nil),      // 1: streamforge.RegisterRequest
	(*RegisterResponse)(nil),     // 2: streamforge.RegisterResponse
	(*Assignment)(nil),           // 3: streamforge.Assignment
	(*HeartbeatRequest)(nil),     // 4: streamforge.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: streamforge.HeartbeatResponse
	(*CheckpointBarrier)(nil),    // 6: streamforge.CheckpointBarrier
	(*CheckpointAck)(nil),        // 7: streamforge.CheckpointAck
	(*Empty)(nil),                // 8: streamforge.Empty
	(*GetAssignmentRequest)(nil), // 9: streamforge.GetAssignmentRequest
	(*ShuffleRequest)(nil),       // 10: streamforge.ShuffleRequest
	nil,                          // 11: streamforge.CheckpointAck.KafkaOffsetsEntry
}
var file_proto_streamforge_proto_depIdxs = []int32{
	3,  // 0: streamforge.RegisterResponse.assignment:type_name -> streamforge.Assignment
	3,  // 1: streamforge.HeartbeatResponse.assignment:type_name -> streamforge.Assignment
	11, // 2: streamforge.CheckpointAck.kafka_offsets:type_name -> streamforge.CheckpointAck.KafkaOffsetsEntry
	0,  // 3: streamforge.ShuffleRequest.event:type_name -> streamforge.Event
	1,  // 4: streamforge.Coordinator.Register:input_type -> streamforge.RegisterRequest
	4,  // 5: streamforge.Coordinator.Heartbeat:input_type -> streamforge.HeartbeatRequest
	9,  // 6: streamforge.Coordinator.GetAssignment:input_type -> streamforge.GetAssignmentRequest
	6,  // 7: streamforge.Worker.PrepareCheckpoint:input_type -> streamforge.CheckpointBarrier
	6,  // 8: streamforge.Worker.CommitCheckpoint:input_type -> streamforge.CheckpointBarrier
	10, // 9: streamforge.Worker.Shuffle:input_type -> streamforge.ShuffleRequest
	2,  // 10: streamforge.Coordinator.Register:output_type -> streamforge.RegisterResponse
	5,  // 11: streamforge.Coordinator.Heartbeat:output_type -> streamforge.HeartbeatResponse
	3,  // 12: streamforge.Coordinator.GetAssignment:output_type -> streamforge.Assignment
	8,  // 13: streamforge.Worker.PrepareCheckpoint:output_type -> streamforge.Empty
	7,  // 14: streamforge.Worker.CommitCheckpoint:output_type -> streamforge.CheckpointAck
	8,  // 15: streamforge.Worker.Shuffle:output_type -> streamforge.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_streamforge_proto_init() }
func file_proto_streamforge_proto_init() {
	if File_proto_streamforge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streamforge_proto_rawDesc), len(file_proto_streamforge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_streamforge_proto_goTypes,
		DependencyIndexes: file_proto_streamforge_proto_depIdxs,
		MessageInfos:      file_proto_streamforge_proto_msgTypes,
	}.Build()
	File_proto_streamforge_proto = out.File
	file_proto_streamforge_proto_goTypes = nil
	file_proto_streamforge_proto_depIdxs = nil
}
